"""tests/mock_data.py - Shared Mock State for Parallel Team Development"""

INITIAL_INPUT_STATE = {
    "selected": {
        "sw": "KIVI",
        "hw": "CXL-PNM",
        "families": {"sw": "KV Quantization", "hw": "CXL Memory Expansion"},
        "rationale": "KIVI represents algorithmic 2-bit quantization while CXL-PNM represents hardware near-memory acceleration.",
    },
    "tech_sw": {},
    "tech_hw": {},
    "domain": {},
    "market": {},
    "stakeholder": {},
    "claims": [],
    "evidence": [],
    "sources": [],
    "audit": {"issues": []},
    "retry_count": {"paper": 0, "market": 0, "stakeholder": 0},
    "trl": {},
    "synthesis": {},
    "report": "",
}

MOCK_STATE = {
    "selected": {
        "sw": "KIVI",
        "hw": "CXL-PNM",
        "families": {"sw": "KV Quantization", "hw": "CXL Memory Expansion"},
        "rationale": "Representative software algorithmic vs hardware near-memory expansion approaches.",
    },
    "tech_sw": {
        "name": "KIVI",
        "mechanism": "Asymmetric 2bit quantization (Key per-channel, Value per-token)",
        "quant_scheme": "2-bit asymmetric; Key per-channel, Value per-token; recent tokens kept in full precision",
    },
    "tech_hw": {
        "name": "CXL-PNM",
        "mechanism": "Full KV cache kept in CXL memory; in-module PNM accelerator selects important token pages and runs attention, removing GPU recall",
        "experiment": "Cycle-level simulation of a 7nm design (simulation, not measured)",
    },
    "domain": {
        "memory_footprint": "KIVI: up to 2.6x less peak memory incl. model weights (Llama/Falcon/Mistral, measured); CXL-PNM: KV cache held in CXL memory (7nm simulation)",
        "infra_change": "KIVI: software-only on existing GPU/HBM; CXL-PNM: requires CXL memory modules with PNM accelerator",
    },
    "market": {
        "key_vendors": ["Samsung", "SK Hynix"],
        "adoption": "CXL Memory Expansion family: Samsung announced commercial readiness of CXL 2.0 DRAM (MKT-01, vendor_claim)",
        "barriers": "KV Quantization: accuracy risk grows with compression ratio; CXL Memory Expansion: new CXL infrastructure required, transfer latency remains",
    },
    "stakeholder": {
        "cloud_ops": "KIVI applies in software on existing GPU/HBM; CXL-PNM requires new CXL/PNM hardware",
        "hw_vendors": "Samsung announced commercial readiness of CXL 2.0 DRAM (MKT-01, vendor_claim)",
    },
    "claims": [
        {
            "id": "DOM-01",
            "perspective": "domain",
            "tech": "KIVI",
            "statement": "KIVI lets Llama, Falcon and Mistral models use up to 2.6x less peak memory (including model weights) with 2-bit KV cache quantization.",
            "kind": "fact",
            "evidence_ids": ["EV-DOM-01"],
            "counter_evidence_ids": [],
            "counter_searched": False,
            "status": "ok",
        },
        {
            "id": "DOM-02",
            "perspective": "domain",
            "tech": "CXL-PNM",
            "statement": "In cycle-level simulation of a 7nm design, the PNM accelerator inside the CXL memory module selects important token pages and performs attention, removing KV cache recall to the GPU.",
            "kind": "simulation",
            "evidence_ids": ["EV-DOM-02"],
            "counter_evidence_ids": [],
            "counter_searched": False,
            "status": "ok",
        },
        {
            "id": "MKT-01",
            "perspective": "market",
            "tech": "CXL-PNM",
            "statement": "Samsung Electronics announced commercial readiness of 256GB CXL 2.0 DRAM in 2024.",
            "kind": "vendor_claim",
            "evidence_ids": ["EV-MKT-01"],
            "counter_evidence_ids": [],
            "counter_searched": True,
            "status": "ok",
        },
    ],
    "evidence": [
        {
            "evidence_id": "EV-DOM-01",
            "source_id": "SRC-PAPER-KIVI",
            "snippet": "With 2-bit KV cache quantization, KIVI enables Llama, Falcon and Mistral models to use 2.6x less peak memory (including model weights) without fine-tuning.",
        },
        {
            "evidence_id": "EV-DOM-02",
            "source_id": "SRC-PAPER-CXL-PNM",
            "snippet": "In our cycle-level simulation of a 7nm design, the PNM accelerator in the CXL memory module selects important token pages and computes attention, eliminating KV cache recall to the GPU.",
        },
        {
            "evidence_id": "EV-MKT-01",
            "source_id": "SRC-MKT-01",
            "snippet": "Samsung Electronics announced commercial readiness of 256GB CXL 2.0 DRAM in 2024.",
        },
    ],
    "sources": [
        {
            "source_id": "SRC-PAPER-KIVI",
            "title": "KIVI: A Tuning-Free Asymmetric 2bit Quantization for KV Cache",
            "publisher": "ICML",
            "date": "2024",
            "url": "https://arxiv.org/abs/2402.02750",
            "source_type": "paper",
            "source_tier": "T1",
        },
        {
            "source_id": "SRC-PAPER-CXL-PNM",
            "title": "CXL-PNM: Processing-near-Memory Acceleration for Large Language Models",
            "publisher": "PACT",
            "date": "2025",
            "url": "https://arxiv.org/abs/2511.00321",
            "source_type": "paper",
            "source_tier": "T1",
        },
        {
            "source_id": "SRC-MKT-01",
            "title": "Samsung CXL 2.0 Press Release",
            "publisher": "Samsung Semiconductor",
            "date": "2024",
            "url": "https://semiconductor.samsung.com/newsroom",
            "source_type": "web",
            "source_tier": "T2",
        },
    ],
    "audit": {"issues": []},
    "retry_count": {"paper": 0, "market": 0, "stakeholder": 0},
    "trl": {
        "KIVI": {
            "tech_trl": "5-6",
            "family_trl": "6-7",
            "confidence": "medium",
            "fallback_reason": None,
            "research_evidence": ["ICML 2024 paper and open-source reference implementation"],
            "adoption_evidence": ["Open-source KIVI implementation (GitHub)"],
        },
        "CXL-PNM": {
            "tech_trl": "3-4",
            "family_trl": "7-8",
            "confidence": "high",
            "fallback_reason": None,
            "research_evidence": ["PACT 2025 7nm cycle-level simulation"],
            "adoption_evidence": ["Samsung and SK Hynix commercial CXL 2.0 DRAM modules"],
        },
    },
    "synthesis": {
        "tradeoffs": "KIVI shrinks the KV cache on existing GPU/HBM with accuracy risk that grows with compression; CXL-PNM keeps full precision by expanding capacity but needs new CXL/PNM hardware and retains transfer latency.",
        "evidence_gaps": [],
    },
    "report": "",
}
