"""tests/mock_data.py - Shared Mock State for Parallel Team Development"""

INITIAL_INPUT_STATE = {
    "selected": {
        "sw": "KIVI",
        "hw": "CXL-PNM",
        "families": {"sw": "KV Quantization", "hw": "CXL Memory Expansion"},
        "rationale": "KIVI represents algorithmic 2-bit quantization while CXL-PNM represents hardware near-memory acceleration.",
    },
    "tech_sw": {},
    "tech_hw": {},
    "domain": {},
    "market": {},
    "stakeholder": {},
    "claims": [],
    "evidence": [],
    "sources": [],
    "audit": {"issues": []},
    "retry_count": {"paper": 0, "market": 0, "stakeholder": 0},
    "trl": {},
    "synthesis": {},
    "report": "",
}

MOCK_STATE = {
    "selected": {
        "sw": "KIVI",
        "hw": "CXL-PNM",
        "families": {"sw": "KV Quantization", "hw": "CXL Memory Expansion"},
        "rationale": "Representative software algorithmic vs hardware near-memory expansion approaches.",
    },
    "tech_sw": {
        "name": "KIVI",
        "mechanism": "Asymmetric 2bit quantization (Key per-channel, Value per-token)",
        "quant_scheme": "Key: per-channel FP2, Value: per-token FP2",
        "workload_sensitivity": "High throughput serving with long context (>8k tokens)",
    },
    "tech_hw": {
        "name": "CXL-PNM",
        "mechanism": "Near-memory processing inside CXL controller",
        "interconnect": "PCIe 5.0 / CXL 2.0 type 3 memory expansion",
        "workload_sensitivity": "Memory-bound LLM serving offloaded to external host memory pool",
    },
    "domain": {
        "memory_footprint": "KIVI: up to 2.6x reduction; CXL-PNM: GPU DRAM footprint offloaded to CXL",
        "latency_impact": "KIVI: minimal decoding latency overhead; CXL-PNM: near-memory reduces bus bottleneck",
        "serving_scalability": "Both expand concurrent batch size in cloud serving environments",
    },
    "market": {
        "adoption": "vLLM evaluating 2bit kernel integration; CXL 2.0 server platforms rolling out",
        "barriers": "KIVI requires specialized kernel integration; CXL requires physical PCIe/CXL server infrastructure",
    },
    "stakeholder": {
        "cloud_ops": "KIVI is zero CAPEX software upgrade; CXL involves hardware server renewal",
        "hw_vendors": "Samsung and SK Hynix actively pushing CXL memory modules",
        "chipmakers": "NVIDIA focuses on HBM bandwidth, CXL acts as cost-effective expansion pool",
    },
    "claims": [
        {
            "id": "DOM-01",
            "perspective": "domain",
            "tech": "KIVI",
            "statement": "KIVI reduces KV cache memory footprint by up to 2.6x with 2-bit quantization on Llama-2-70B.",
            "kind": "fact",
            "evidence_ids": ["EV-DOM-01"],
            "counter_evidence_ids": [],
            "counter_searched": False,
            "status": "ok",
        },
        {
            "id": "DOM-02",
            "perspective": "domain",
            "tech": "CXL-PNM",
            "statement": "CXL-PNM near-memory processing simulation shows 3.1x energy efficiency improvement in attention layers.",
            "kind": "simulation",
            "evidence_ids": ["EV-DOM-02"],
            "counter_evidence_ids": [],
            "counter_searched": False,
            "status": "ok",
        },
        {
            "id": "MKT-01",
            "perspective": "market",
            "tech": "CXL-PNM",
            "statement": "Samsung Electronics announced mass production readiness of CXL 2.0 DRAM.",
            "kind": "fact",
            "evidence_ids": ["EV-MKT-01"],
            "counter_evidence_ids": [],
            "counter_searched": True,
            "status": "ok",
        },
    ],
    "evidence": [
        {
            "evidence_id": "EV-DOM-01",
            "source_id": "SRC-PAPER-KIVI",
            "snippet": "Under 2-bit quantization, KIVI reduces KV cache size by up to 2.6x on Llama-2-70B without fine-tuning.",
        },
        {
            "evidence_id": "EV-DOM-02",
            "source_id": "SRC-PAPER-CXL-PNM",
            "snippet": "Cycle-accurate simulation of CXL-PNM controller demonstrates 3.1x energy efficiency gain in attention pooling.",
        },
        {
            "evidence_id": "EV-MKT-01",
            "source_id": "SRC-MKT-01",
            "snippet": "Samsung Electronics announced commercial readiness of 256GB CXL 2.0 DRAM in 2024.",
        },
    ],
    "sources": [
        {
            "source_id": "SRC-PAPER-KIVI",
            "title": "KIVI: A Tuning-Free Asymmetric 2bit Quantization for KV Cache",
            "publisher": "ICML",
            "date": "2024",
            "url": "https://arxiv.org/abs/2402.02750",
            "source_type": "paper",
            "source_tier": "T1",
        },
        {
            "source_id": "SRC-PAPER-CXL-PNM",
            "title": "CXL-PNM: Processing-near-Memory Acceleration for Large Language Models",
            "publisher": "PACT",
            "date": "2024",
            "url": "https://doi.org/10.1109/PACT",
            "source_type": "paper",
            "source_tier": "T1",
        },
        {
            "source_id": "SRC-MKT-01",
            "title": "Samsung CXL 2.0 Press Release",
            "publisher": "Samsung Semiconductor",
            "date": "2024",
            "url": "https://semiconductor.samsung.com/newsroom",
            "source_type": "web",
            "source_tier": "T2",
        },
    ],
    "audit": {"issues": []},
    "retry_count": {"paper": 0, "market": 0, "stakeholder": 0},
    "trl": {
        "KIVI": {
            "tech_trl": "5-6",
            "family_trl": "6-7",
            "confidence": "medium",
            "fallback_reason": None,
            "research_evidence": ["ICML 2024 paper open-source implementation"],
            "adoption_evidence": ["vLLM 2-bit kernel pull requests and evaluations"],
        },
        "CXL-PNM": {
            "tech_trl": "3-4",
            "family_trl": "7-8",
            "confidence": "high",
            "fallback_reason": None,
            "research_evidence": ["PACT 2024 7nm cycle-accurate simulation"],
            "adoption_evidence": ["Samsung and SK Hynix commercial CXL 2.0 DRAM modules"],
        },
    },
    "synthesis": {
        "tradeoffs": "KIVI provides immediate zero-CAPEX memory savings via algorithmic quantization, whereas CXL-PNM provides scalable hardware memory expansion at higher CAPEX.",
        "evidence_gaps": [],
    },
    "report": "",
}
